(function(a,c,t,s){"use strict";let g=[];t.findByProps("sendMessage","editMessage");const l=t.findByProps("getMessage","getMessages");t.findByProps("getChannel"),t.findByProps("getCurrentUser","getUser");const p=t.findByName("MessageHeader"),h=t.findByName("MessageContent");function u(n){return n?.messageReference&&n?.type===19}function d(n){const i=n?.messageReference;if(!i)return null;const{guild_id:e,channel_id:r,message_id:o}=i,f=l?.getMessage(r,o);return{guildId:e,channelId:r,messageId:o,originalMessage:f,originalLink:`https://discord.com/channels/${e||"@me"}/${r}/${o}`}}function M(){if(!p){s.logger.warn("Could not find MessageHeader component");return}const n=c.before("render",p.prototype,function(i){const e=this.props?.message;if(!(!e||!u(e)||!d(e))&&this.props?.children){const r=function(o){o?.props?.children==="SERVER"&&(o.props.children="FORWARDED",s.logger.log("Replaced SERVER tag with FORWARDED")),Array.isArray(o?.props?.children)&&o.props.children.forEach(r)};Array.isArray(this.props.children)?this.props.children.forEach(r):r(this.props.children)}});g.push(n)}function y(){if(!h){s.logger.warn("Could not find MessageContent component");return}const n=c.after("render",h.prototype,function(i,e){const r=this.props?.message;if(!r||!u(r))return e;const o=d(r);if(!o)return e;if(o.originalMessage?.content){const f=`${o.originalMessage.content.split(`
`).map(function(F){return`> ${F}`}).join(`
`)}

[Original Message](${o.originalLink})`;e?.props&&(e.props.children=f,s.logger.log("Modified forwarded message content"))}return e});g.push(n)}function R(){if(!l?.getMessage){s.logger.warn("Could not find MessageStore.getMessage");return}const n=c.after("getMessage",l,function(i,e){if(!e||!u(e))return e;const r=d(e);if(!r?.originalMessage)return e;const o={...e,content:m(r.originalMessage.content,r.originalLink),author:{...e.author,tag:e.author?.tag?.replace("SERVER","FORWARDED")||e.author?.tag}};return s.logger.log("Modified forwarded message in store"),o});g.push(n)}function m(n,i){return n?`${n.split(`
`).map(function(e){return`> ${e}`}).join(`
`)}

[Original Message](${i})`:""}var E={onLoad:function(){s.logger.log("Forward Fixer plugin loaded!");try{R(),M(),y(),s.logger.log("Successfully patched message functions")}catch(n){s.logger.error("Failed to patch message functions:",n)}},onUnload:function(){s.logger.log("Forward Fixer plugin unloaded!"),g.forEach(function(n){try{n()}catch(i){s.logger.error("Failed to remove patch:",i)}}),g=[]}};return a.default=E,Object.defineProperty(a,"__esModule",{value:!0}),a})({},vendetta.patcher,vendetta.metro,vendetta);
